version: "3.9"


services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: CBV
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True